export default {
  emptyPhoneNo: 'Please enter Phone Number',
  invalidPhoneNo: 'Please enter valid Phone Number',
  emptyOTP: 'Please enter OTP',
  invalidOTP: 'Please enter valid OTP',
  emptyName: 'Please enter Name',
  invalidName: 'Please enter valid Name',
  emptyEmail: 'Please enter Email',
  invalidEmail: 'Please enter valid Email',
  emptyPin: 'Please enter Pin',
  invalidPin: 'Please enter valid Pin',
  emptyConfirmPin: 'Please enter Confirm Pin',
  pinNotMatch: 'Confirm pin does not match with pin',
  emptyState: 'Please select a State',
  emptyCity: 'Please select a City',
  emptyDate: 'Please select a Date',
  emptyProfile: 'Please select a Profile Image',
  emptyRequestFor: 'Please enter Request For',
  emptyAdditionalDetail: 'Please enter Additional Detail',
  emptyUploadImage: 'Please select a Image',
  emptyReason: 'Please enter Reason',
  invalidReason: 'Please enter valid Reason',
  emptyMessage: 'Please enter your message',
  invalidMessage: 'Please enter valid message',
};
