export default {
  montserratBlack: 'Montserrat-Black',
  montserratBlackItalic: 'Montserrat-BlackItalic',
  montserratBold: 'Montserrat-Bold',
  montserratBoldItalic: 'Montserrat-BoldItalic',
  montserratExtraBold: 'Montserrat-ExtraBold',
  montserratExtraBoldItalic: 'Montserrat-ExtraBoldItalic',
  montserratExtraLight: 'Montserrat-ExtraLight',
  montserratExtraLightItalic: 'Montserrat-ExtraLightItalic',
  montserratItalic: 'Montserrat-Italic',
  montserratLight: 'Montserrat-Light',
  montserratLightItalic: 'Montserrat-LightItalic',
  montserratMedium: 'Montserrat-Medium',
  montserratMediumItalic: 'Montserrat-MediumItalic',
  montserratRegular: 'Montserrat-Regular',
  montserratSemiBold: 'Montserrat-SemiBold',
  montserratSemiBoldItalic: 'Montserrat-SemiBoldItalic',
  montserratThin: 'Montserrat-Thin',
  montserratThinItalic: 'Montserrat-ThinItalic',
  poppinsBold: 'Poppins-Bold',
  poppinsMedium: 'Poppins-Medium',
  poppinsRegular: 'Poppins-Regular',
  poppinsSemiBold: 'Poppins-SemiBold',
  alegreyaSansBold: 'AlegreyaSans-Bold',
  alegreyaSansRegular: 'AlegreyaSans-Regular',
};
