export default {
  banner: require('./image/banner.png'),
  user: require('./image/user.png'),
  coin: require('./image/coin.png'),
  doToss: require('./image/doToss.png'),
  leftArrow: require('./image/leftArrow.png'),
  rightArrow: require('./image/rightArrow.png'),
  academic: require('./image/academic.png'),
  coaching: require('./image/coaching.png'),
  event: require('./image/event.png'),
  playZone: require('./image/playZone.png'),
  school: require('./image/school.png'),
  sports: require('./image/sports.png'),
  success: require('./image/success.png'),
  fail: require('./image/fail.png'),
  shoppingCart: require('./image/shopBag.png'),
  sort: require('./image/sort.png'),
  filter: require('./image/filter.png'),
  crossPrimary: require('./image/crossPrimary.png'),
  goIn: require('./image/goIn.png'),
  discountRed: require('./image/discountRed.png'),
  minus: require('./image/minus.png'),
  plus: require('./image/plus.png'),
  arrowIn: require('./image/arrowIn.png'),
  neonBall: require('./image/neonBall.png'),
  roundStarFill: require('./image/roundStarFill.png'),
  roundStar: require('./image/roundStar.png'),
  cock: require('./image/cock.png'),
  simpleLogo: require('./image/simpleLogo.png'),
  noImage: require('./image/noImage.png'),
  // dollar: require('./image/dollar.png'),
  dollar: require('./image/nexusCoin.png'),
  dollarTemp: require('./image/dollarTemp.png'),
  nexusCoin: require('./image/nexusCoin.png'),
  nx2: require('./image/nx2.png'),
  redeemPoint: require('./image/redeemPoint.png'),
  confetti: require('./image/confetti.png'),
};
